version: '3'
services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    expose:
      - $DB_PORT

  backend:
    build:
      context: ../..
      dockerfile: ./infra/Dockerfile
    command: bash -c "chmod +x start.sh && ./start.sh"
    restart: always
    depends_on:
      - db
    env_file:
      - ../../.env
    volumes:
      - static:/app/static/
      - media:/app/media/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    env_file:
      - ../../.env

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
    env_file:
      - ../../.env

  celery_worker:
    build:
      context: ../..
      dockerfile: ./infra/Dockerfile
    command: bash -c "celery -A funtech_proj.celery worker --loglevel=info"
    volumes:
      - media:/src/media/
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      - backend
    env_file:
      - ../../.env

volumes:
  db_data:
  static:
  media:
