version: '3'
services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    expose:
      - $DB_PORT

  backend:
    build:
      context: ../..
      dockerfile: ./infra/Dockerfile
    command: bash -c "chmod +x start.sh && ./start.sh"
    restart: always
    depends_on:
      - db
    env_file:
      - ../../.env
    volumes:
      - static:/app/static/
      - media:/app/media/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/


volumes:
  db_data:
  static:
  media:
