name: CI/CD

on: [push]

jobs:

  tests:
    uses: ./.github/workflows/tests.yml

  build_and_push_to_docker_hub:
    uses: ./.github/workflows/build_push.yml
    with:
      back_or_front: backend


  #server_environment:
  #deploy:
